files:
  metadata:
    - data/raw/abcd_p_demo.csv
    - data/raw/mh_p_cbcl.csv
    - data/raw/mri_y_adm_info.csv
    - data/raw/mri_y_qc_auto_post.csv
    - data/raw/RVI_groups.csv
  imaging:
    - data/raw/mri_y_dti_fa_is_at.csv
    - data/raw/mri_y_dti_ld_is_at.csv
    - data/raw/mri_y_dti_md_is_at.csv
    - data/raw/mri_y_dti_td_is_at.csv
    - data/raw/mri_y_smr_area_dsk.csv
    - data/raw/mri_y_smr_area_dst.csv
    - data/raw/mri_y_smr_sulc_dsk.csv
    - data/raw/mri_y_smr_sulc_dst.csv
    - data/raw/mri_y_smr_thk_dsk.csv
    - data/raw/mri_y_smr_thk_dst.csv
    - data/raw/mri_y_smr_vol_aseg.csv
    - data/raw/mri_y_smr_vol_dsk.csv
    - data/raw/mri_y_smr_vol_dst.csv

columns:
  mapping:
    id: src_subject_id
    timepoint: eventname
    sex: demo_sex_v2
    sex_mapped: sex_mapped
    age: demo_brthdat_v2
    t_score: cbcl_scr_dsm5_anxdisord_t
    research_group: anx_group  # Automatically set by config.py based on run_name
    scanner_manufacturer: mri_info_manufacturer
    scanner_serial: mri_info_deviceserialnumber
    qc: apqc_smri_topo_ndefect
  metadata:
    - src_subject_id
    - eventname
    - demo_sex_v2
    - demo_brthdat_v2
    - cbcl_scr_dsm5_anxdisord_t
    - mri_info_manufacturer
    - mri_info_deviceserialnumber
    - apqc_smri_topo_ndefect
    # group_last_final automatically added for psychosis runs by config.py
  derived:
    - sex_mapped
    - anx_group  # Automatically set by config.py based on run_name
  imaging:
    dti:
      prefixes:
        - dmri
    smri_area:
      mrisdp_range: [303, 453]
      prefixes:
        - smri_area_cdk
        - mrisdp
    smri_thk:
      mrisdp_range: [1, 151]
      prefixes:
        - smri_thk_cdk
        - mrisdp
    smri_sulc:
      mrisdp_range: [152, 302]
      prefixes:
        - smri_sulc_cdk
        - mrisdp
    smri_vol:
      mrisdp_range: [454, 604]
      prefixes:
        - smri_vol_cdk
        - smri_vol_scs
        - mrisdp
timepoints:
  baseline: baseline_year_1_arm_1
  year2: 2_year_follow_up_y_arm_1
  year3: 3_year_follow_up_y_arm_1
  year4: 4_year_follow_up_y_arm_1

qc_thresholds:
  surface_holes_max: 62

derived:
  sex:
    source: sex
    output: sex_mapped
    map:
      1: male
      2: female
      "1": male
      "2": female
  anxiety:
    source: t_score
    output: anx_group
    thresholds:
      control_max: 59
      subclinical_max: 64
    labels:
      control: Control
      subclinical: Subclinical
      clinical: Clinical
  psychosis:
    source: group_last_final  # Assuming column name in RVI_groups.csv
    output: psych_group
    map:
      1: Clinical
      2: Subclinical
      3: Subclinical
      4: Subclinical
      5: Control
      "1": Clinical
      "2": Subclinical
      "3": Subclinical
      "4": Subclinical
      "5": Control

missing:
  require_complete_metadata:
    - age
    - t_score
    - scanner_manufacturer
    - scanner_serial
    - research_group  # Will use anx_group or psych_group based on mapping above
  require_complete_families:
    - dti

splits:
  train: 0.8
  val: 0.1
  test: 0.1
  stratify: research_group  # Will use the configured research question grouping
